version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:scm
    steps:
      - checkout
      - run:
    name: Upload server
    command: |
      chmod +x .circleci/upload_server.sh
      ./.circleci/upload_server.sh

workflows:
  version: 2
  build_and_test:
  jobs:
    - build:
  filters:
  branches:
  only: master
